# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08fd84ed1cd08ea4d4c555a33ad8afa42e00b8d4f3bdfd81ed72605ceae2f593cefd86ff7aa0420b3ae4d8191b0a90568057d4dc3df9a11edf183893d59e5c98

test:
  secret_key_base: e1e4a5956061caac2d23c0a24f4aa38d6be837a11d88f43c390625fab5fb31e58a3ede9ffcbc9bc4d84bcd32cd0a0a58eb7ff889f8ee85d6bb57bd1a51a9bc9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
